# Generated by Django 2.2.27 on 2022-04-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of event', max_length=100)),
                ('description', models.TextField(help_text='description about event')),
                ('location', models.TextField(blank=True, help_text='location of the event')),
                ('event_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
