# Generated by Django 2.2.27 on 2022-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearcatE', '0002_delete_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='location',
            field=models.TextField(blank=True, help_text='location of the event'),
        ),
    ]
